debug: true
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource: 
    url: jdbc:mysql://127.0.0.1:3306/tr1705_db?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid: 
      filters:
        - stat
        - wall
        - log4j
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: update    
        
#mybatis\u7684\u914D\u7F6E
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: cn.gson.kuangjia.model.pojos
  
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql 
    
  